server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/nini1304/server-config.git
          default-label: main
  application:
    name: ms-config-server
