server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/nini1304/server-config.git
          default-label: main
          ignoreLocalSshSettings: true
          hostkey: AAAAB3NzaC1yc2EAAAADAQABAAABgQC2gi5YioFkqXOEXFMOb4T7HUXNwr0VB15ICdrsNeRGr1tR+iw6SfDs/SxScv6m64LGfCYmGVTFHPvmSWAJwW+F0KuOqnQ9H94jqEu20/DgW3LCy3M3RAjb9pU0OCmDwK8z8aQI5uZVD7oMZ6yZZayj/46TAxCwNiq82rqqKmPFgZTo3ZtvKUGZAhFsA7lHAFPDb2zF6lFPTYYadZ928iPbtNGys6Yq0sXZeoRcKyUeNedwVg9/En6MtjPRyc6VKWj7GqNxM0LcIJhBnvex2CP2aGzigGkeWoD+8BaouQt86mFzAlNz7VG8PSgoYzEbN/QVPZW6KBEACdykw6RfKusr1n43CreAP8GUu/qiKUMaKqzOEMHGQTLCAbIdJ4SmRoavUwXfOCEj4zAYF0k/J2MWSN40l/ExszkathzbPEbzH50rfIGGnaMBOy/3MYGbHQbKx57Cg+qO7U+MpQt6JrM898YguXJKkwMIdF2OgM2ckKGQ3f4QwVk1VHNA2v8lisE= geral@DESKTOP-71UTI3R
          hostKeyAlgorithm: ssh-rsa
          privateKey: |
            -----BEGIN OPENSSH PRIVATE KEY-----
            b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAABlwAAAAdzc2gtcn
            NhAAAAAwEAAQAAAYEAtoIuWIqBZKlzhFxTDm+E+x1FzcK9FQdeSAna7DXkRq9bUfosOknw
            7P0sUnL+puuCxnwmJhlUxRz75klgCcFvhdCrjqp0PR/eI6hLttPw4FtywstzN0QI2/aVND
            gpg8CvM/GkCObmVQ+6DGesmWWso/+OkwMQsDYqvNq6qipjxYGU6N2bbylBmQIRbAO5RwBT
            w29sxepRT02GGnWfdvIj27TRsrOmKtLF2XqEXCslHjXncFYPfxJ+jLYz0cnOlSlo+xqjcT
            NC3CCYQZ73sdgj9mhs4oBpHlqA/vAWqLkLfOphcwJTc+1RvD0oKGMxGzf0FT2VuigRAAnc
            pMOkXyrrK9Z+Nwq3gD/BlLv6oilDGiqszhDBxkEywgGyHSeEpkaGr1MF3zghI+MwGBdJPy
            djFkjeNJfxMbM5GrYc2zxG8x+dK3yBhp2jATsv9zGBmx0GyseewoPqju1PjKULeiazPPfG
            ILlySpMDCHRdjoDNnJChkN3+EMFZNVRzQNr/JYrBAAAFkL2Aa5O9gGuTAAAAB3NzaC1yc2
            EAAAGBALaCLliKgWSpc4RcUw5vhPsdRc3CvRUHXkgJ2uw15EavW1H6LDpJ8Oz9LFJy/qbr
            gsZ8JiYZVMUc++ZJYAnBb4XQq46qdD0f3iOoS7bT8OBbcsLLczdECNv2lTQ4KYPArzPxpA
            jm5lUPugxnrJllrKP/jpMDELA2KrzauqoqY8WBlOjdm28pQZkCEWwDuUcAU8NvbMXqUU9N
            hhp1n3byI9u00bKzpirSxdl6hFwrJR4153BWD38Sfoy2M9HJzpUpaPsao3EzQtwgmEGe97
            HYI/ZobOKAaR5agP7wFqi5C3zqYXMCU3PtUbw9KChjMRs39BU9lbooEQAJ3KTDpF8q6yvW
            fjcKt4A/wZS7+qIpQxoqrM4QwcZBMsIBsh0nhKZGhq9TBd84ISPjMBgXST8nYxZI3jSX8T
            GzORq2HNs8RvMfnSt8gYadowE7L/cxgZsdBsrHnsKD6o7tT4ylC3omszz3xiC5ckqTAwh0
            XY6AzZyQoZDd/hDBWTVUc0Da/yWKwQAAAAMBAAEAAAGBAKDAMQoTlLyQ9ApVN2KznzF/Kw
            h8ygZHoydYZtc+8H3B3nFqJKKClg5nQC6u0tU7AsjIeOF91kh3qve/ETQGiLAYh8L1J8Te
            2M4XYfj63GMAqSgiAq1e41665dhEz2wYvzjFUXH1zlKFs51Rg5jpERKx+WZLgNt0GliVX2
            yaQZ6o7/vblRhoAjs+sxGshfiftSeicPAx3sQ2yDNt/rLJvAO8VCdOTMHTPCi93O9BoUPm
            vp8XbjbCl2xg32uckLSY7z0jUmJ6djKEDSfmijfTsr8kKiLCdGUeHJSPrYPgck0VX7bGrU
            pPqxuo0Nxj9Y52O+/dMMGkGEO/1rP5ampToKy2soG1BvUmlnR9gz+fdus8f+DvZLVK6GtD
            oSlQ4/pIVyPA6pOzBEAMl+xeN8Fqa/nt2QGO4TYV7va4OtsIi6KHchAf0i92Qfg5C9Ngpl
            9Bao6ASH80S8WnroYPCs84OWHMrEi0iwBpJ/ZwQXUHIUuqpA2ioowKkoEaSSYxAx6KsQAA
            AMEAg0Sf9SxYVWNnoPvkFJFy3BgkPX5ZDUOQc8vJIYGtoaiNUF3FdbLn3nP+xBMg/A7i65
            G8A57Z16zKNwetRY1ajnrocrTeEAM7TRwOkIK+F8FcSOlqxddX+RkHv4ccZH7bVG2C5RNe
            W9jxOsqijDAxpEW6sES9dcUzxLAYgjVK8y61M8pH3rXwbp0roLQb7BIBMBqo9hv1lPrwdS
            YAeaY9lwF9+FP4dc4pINQDdkWP0rvw5CHcbb00Za2y4OErA7HDAAAAwQDlqXS6Z2NRsxEO
            TX1kr+hQajjRJpR9aF2+cS7KxrsmS0zrHOtOdR1xFnPd7aRBrcbNH/6IYQdFGNmUkxkqB8
            Jnzth6rBZ4nk1ymbpnUNDAtWIGNtHifNNaKezaqdsdgKauM9k0CjHJuBub0CbpBlxG43Pz
            xlbJgHvxkjU1mrq1g9P8/lInwnRKojNK7wrWrgI1KyrRHuroC8DZXYTrpUZLfTG5gzAVjz
            J+XmiI++577JiksHAwdF0zYSXIvkFyVyMAAADBAMtwXlrHAnKqIMW06p4zak8FRpxEWghE
            kOf95OyXOqdfmrrsHLINMVoNgwFDEorUg0qqQ0YM0S1X9i9kndpfXzB0/2hbZcCPHNdF2v
            wo1MrMihG0Vu+Z4PdI8n3SGNGA/GMmhq02YRW5pzkbNdoDYKjbkMAwg/HFwoz26QixClZ3
            PVwuhifhFVo21WnOFaAxT8Phkh7JX69zpGNbCQn+wMoR8T7+HTc/1/3oFT+qsygJ1/XH59
            JexBN9yRysP5vmywAAABVnZXJhbEBERVNLVE9QLTcxVVRJM1IBAgME
            -----END OPENSSH PRIVATE KEY-----
  application:
    name: ms-config-server
encrypt:
  key: jkfgjghgjfkd$fgh%hjgjh$$hjfhjg#hgj
